// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8WBQWrkzUMuYGRAmKw2-BC_al1b4VMhI',
    appId: '1:373356233353:web:fc37e9b059863cb1b2fc58',
    messagingSenderId: '373356233353',
    projectId: 'captalis-71b58',
    authDomain: 'captalis-71b58.firebaseapp.com',
    storageBucket: 'captalis-71b58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVps6Fejv6ZVBMiVHHMF0bk-a0eSioBK8',
    appId: '1:373356233353:android:2c3fbc577fc131adb2fc58',
    messagingSenderId: '373356233353',
    projectId: 'captalis-71b58',
    storageBucket: 'captalis-71b58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVzZXZ8fEMj_-YZc1fKM5RwLH6gWo2ekw',
    appId: '1:373356233353:ios:dca91f3c4da2db31b2fc58',
    messagingSenderId: '373356233353',
    projectId: 'captalis-71b58',
    storageBucket: 'captalis-71b58.firebasestorage.app',
    iosBundleId: 'com.example.captalis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVzZXZ8fEMj_-YZc1fKM5RwLH6gWo2ekw',
    appId: '1:373356233353:ios:dca91f3c4da2db31b2fc58',
    messagingSenderId: '373356233353',
    projectId: 'captalis-71b58',
    storageBucket: 'captalis-71b58.firebasestorage.app',
    iosBundleId: 'com.example.captalis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8WBQWrkzUMuYGRAmKw2-BC_al1b4VMhI',
    appId: '1:373356233353:web:77d249232656f693b2fc58',
    messagingSenderId: '373356233353',
    projectId: 'captalis-71b58',
    authDomain: 'captalis-71b58.firebaseapp.com',
    storageBucket: 'captalis-71b58.firebasestorage.app',
  );

}